### ISSUE TITLE
Analisi API, endpoints e fetch

### ISSUE THREAD

**Issue by simoneschifano** [simoneschifano/final-project-b-0423#2]
Analisi delle API da utilizzare, endpoints, fetch, env

**Comment by SoniaGrassia** [comment]
//BASE_URL che permette di inserire le query per personalizzare la ricerca
https://api.coingecko.com/api/v3/coins/markets?...

//tutti i dati di mercato delle monete in ordine DECRESCENTE secondo il MARKET_CAP
'GET' \ 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en'

//tutti i dati di mercato delle monete in ordine CRESCENTE secondo il MARKET_CAP
'GET' \ 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_asc&per_page=100&page=1&sparkline=false&locale=en'

//Include la percentuale di variazione del prezzo in 24h
'GET' \ 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false&price_change_percentage=24h&locale=it'
------------------------------------------------------------
//BASE_URL per ottenere i dati di mercato storici che includono prezzo, capitalizzazione di mercato e volume 24 ore su 24
https://api.coingecko.com/api/v3/coins/{id}/market_chart?

//Filtro eseguito su id=bitcoin, valuta col dollaro americano, variazione in 7 giorni, giornaliera
'GET' \ 'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=7&interval=daily
------------------------------------------------------------
//lista delle categorie
'GET' \ 'https://api.coingecko.com/api/v3/coins/categories/list'

//lista delle categorie delle monete con i relativi dati di mercato, continene anche le top 3 coins  (possibilità di scegliere i parametri di ordinamento
 -> market_cap_desc (default), market_cap_asc, name_desc, name_asc, market_cap_change_24h_desc and market_cap_change_24h_asc)
'GET' \ 'https://api.coingecko.com/api/v3/coins/categories?order=...
------------------------------------------------------------
//Le 7 monete di tendenza su CoinGecko più ricercate dagli utenti nelle ultime 24 ore (ordinate per prime dalle più popolari)
'GET' \ 'https://api.coingecko.com/api/v3/search/trending'
----------------------------------------------------------
//dati globali sulle criptovalute
'GET' \ 'https://api.coingecko.com/api/v3/global'
-----------------------------------------------------------
//Ricerca per nome delle monete, categorie e mercati elencati in ordine CRESCENTE secondo il Market Cap
'GET' \ 'https://api.coingecko.com/api/v3/search?query=nomeDellaRicerca
