### ISSUE TITLE
Analisi e creazione components

### ISSUE THREAD

**Issue by simoneschifano** [simoneschifano/final-project-b-0423#3]
- Analisi dei componenti con priorità e complessità
- Scaffolding e creazione componenti e style
- Sviluppo iniziale componenti

**Comment by bennina** [comment]
Ciao @Franceschio, io ho pensato a questa struttura. Ti viene in mente altro? 
Pagine e componenti 

Pagine
ALL CRYPTO
ACCOUNT
Wallet
WATCHLIST
LOGIN
CRYPTO:ID
DASHBOARD

componenti

Sidebar
Header
Card 
Button
Graphics -> pie - bar - line
login form
switcher theme

**Comment by Franceschio** [comment]
ciao @bennina ho fatto anche qualche componente in più
